#ifndef NUBBLE_USER_CONFIG_H
#define NUBBLE_USER_CONFIG_H

// Finer-grained RGB lighting control
#undef RGBLIGHT_ANIMATIONS
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_BREATHING

#define RGBLIGHT_SLEEP

#endif // NUBBLE_USER_CONFIG_H
